### PR TITLE
testing pr on harshalhonde's fork.

### PR DESCRIPTION
**Pull request by PBJI**
image

This kind of bugs needs to be resolved seperately, I'll still suggest to first develop this project on your fork @harshalhonde21  and then merge it after a satisfactory functionality is achieved, then we can allow others to contribute. The work will be more faster, please try to understand.

@NitkarshChourasia, do you agree?

### CODE REVIEW

**Comment by NitkarshChourasia** [comment]
@PBJI @harshalhonde21 You guys are the leaders.
I am okay with everything.

**Comment by PBJI** [comment]
@harshalhonde21 and @NitkarshChourasia, we will be working here from now till we finish achieve satisfactory results.

**Comment by harshalhonde21** [comment]
okk i satisfy what you say @PBJI we will work here only and then whole work over then we create pr

**Comment by PBJI** [comment]
@harshalhonde21 thanks, lets do it. then.....

**Comment by PBJI** [comment]
@NitkarshChourasia and @harshalhonde21 I am working on Projects.jsx page currently.

**Comment by harshalhonde21** [comment]
Is there any need to build profile page login and signup @PBJI ?

**Comment by PBJI** [comment]
@harshalhonde21 not right now atleast.

**Comment by harshalhonde21** [comment]
@PBJI  did you see navbar and footer is it satisfy?

**Comment by PBJI** [comment]
@harshalhonde21 going good. let's keep developing.

**Comment by harshalhonde21** [comment]
if you want any changes please free to change it

**Comment by harshalhonde21** [comment]
should I start working on the Home section and develop stunning animated home page

**Comment by PBJI** [comment]
@harshalhonde21 yes, go ahead. also @NitkarshChourasia you are free to change the appearance and css as per your liking but just keep updating us constantly so that we adopt to those changes.

**Comment by harshalhonde21** [comment]
@PBJI should I host this now only and we can see it in browser and when we changing this the changes also done in hosted website also?

**Comment by PBJI** [comment]
@harshalhonde21 yes yes.

**Comment by harshalhonde21** [comment]
And listen @PBJI and @NitkarshChourasia always sync the changes before starting the coding at every time otherviews the conlifts should come

**Comment by PBJI** [comment]
@harshalhonde21 where are you defining --color-5, 4, 1 and 3?

**Comment by harshalhonde21** [comment]
no didn't define that I want to define it furthere when need

**Comment by PBJI** [comment]
@harshalhonde21 sure.

**Comment by NitkarshChourasia** [comment]
@PBJI @harshalhonde21 just tell me when to start working and on what to work.
Okay?!
And please avoid this github discussions, can we have other alternatives?!
This is so much confusing.

**Comment by NitkarshChourasia** [comment]
This is good per PR, not for **a project**.

**Comment by NitkarshChourasia** [comment]
@PBJI @harshalhonde21

**Comment by PBJI** [comment]
@NitkarshChourasia yes it is confusing to be honest but the project is small and I don't think there is any need to setup any overheads like communication channels. During backend project though we would really require a com channel. But not now,

 and right now you should probably work on experimenting with the home page and thinking about how the front-end should be displaying information there. 

Like for example status related to the repository, current contributors etc. and roughly create a dummy structure with dummy data for that, later we'll integrate it with backend. css theme decided previously should be followed, nothing fancy.

**Comment by PBJI** [comment]
By tomorrow or day after we'll need to wind up with all the pages linked on the nav bar except for profile and login. @harshalhonde21 am I right ?

**Comment by PBJI** [comment]
@NitkarshChourasia work on Home.jsx

**Comment by PBJI** [comment]
I'll finish Projects.jsx by tonight.

**Comment by harshalhonde21** [comment]
@PBJI linking of pages is already done by me you just go to page section and start doing the work

**Comment by NitkarshChourasia** [comment]
@PBJI Actually. I will be using different libraries for CSS.
So, it is just a matter of refinement taste.
Hard - coding is not feasible in actual applied world.
But, still one must know the basics.

**Comment by NitkarshChourasia** [comment]
@PBJI CSS would be improved, better, with time.

**Comment by harshalhonde21** [comment]
Which library are u using ?

**Comment by PBJI** [comment]
@NitkarshChourasia sure.

**Comment by NitkarshChourasia** [comment]
Which library are u using ?

Library is not the deal, whatever you are comfortable with, works fine.

**Pull request merged**
